# iLuminara-Core Cloud Run Service Configuration
# Ensures health data never touches public internet
# Compliance: HIPAA, Kenya DPA isolation requirements

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: iluminara-frontend
  labels:
    app: iluminara
    component: frontend
    compliance: hipaa-kdpa
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/vpc-access-connector: iluminara-vpc-connector
    run.googleapis.com/vpc-access-egress: private-ranges-only
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: iluminara-frontend-sa@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/iluminara-frontend:latest
        
        ports:
        - name: http1
          containerPort: 8080
        
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_ENDPOINT
          value: "https://iluminara-backend-HASH-uc.a.run.app"
        - name: JURISDICTION
          value: "KDPA_KE"
        - name: SOVEREIGNTY_ZONE
          value: "africa-south1"
        
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "512Mi"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 1
          timeoutSeconds: 3
          failureThreshold: 30
  
  traffic:
  - percent: 100
    latestRevision: true

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: iluminara-backend
  labels:
    app: iluminara
    component: backend
    compliance: hipaa-kdpa
  annotations:
    run.googleapis.com/ingress: internal
    run.googleapis.com/vpc-access-connector: iluminara-vpc-connector
    run.googleapis.com/vpc-access-egress: all-traffic
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: iluminara-backend-sa@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/iluminara-backend:latest
        
        ports:
        - name: http1
          containerPort: 8501
        - name: api
          containerPort: 8080
        
        env:
        - name: NODE_ID
          value: "CLOUD-ORACLE-01"
        - name: JURISDICTION
          value: "KDPA_KE"
        - name: SOVEREIGNTY_ZONE
          value: "africa-south1"
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: ENABLE_TAMPER_PROOF_AUDIT
          value: "true"
        - name: CRYPTO_SHREDDER_ENABLED
          value: "true"
        
        resources:
          limits:
            cpu: "4000m"
            memory: "8Gi"
          requests:
            cpu: "2000m"
            memory: "4Gi"
        
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
  
  traffic:
  - percent: 100
    latestRevision: true
